### ISSUE TITLE
Category label should determine what Tags show up on the front page

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4j-contrib/graphgist-cms#33]

**Comment by cheerfulstoic** [comment]
Is this want we want in the light of #34 ?  Are there categories that we don't want to show?

**Comment by jexp** [comment]
The idea was to limit it to relevant categories on the front page and have a separate full page with all of them?

**Comment by cheerfulstoic** [comment]
Cool, can do!  I just finished with the "all graphgists" page, so I'll work on this next

**Comment by jexp** [comment]
yay, thanks !!

**Comment by cheerfulstoic** [comment]
This is now done.  I actually decided to use a `front_page` property on the `Domain` and `UseCase` nodes because it seemed more natural.  It would be really easy to change if desired.

For now I've set that property on all `Domain` and `UseCase` nodes, but if you give me a list of what should stay on the front page I can remove it from the others
