### ISSUE TITLE
When submitting a gist, allow multiples via drop-down and a list of currently selected domains/usecases

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4j-contrib/graphgist-cms#40]

**Comment by cheerfulstoic** [comment]
Done!  Worked out a cypher query that also `UNWIND`s the list of strings and creates relationships to Domains/UseCases

**Comment by jexp** [comment]
Could we put the individual tags side by side in a row, then the other form elements are not pushed down until we filled the line?

**Comment by cheerfulstoic** [comment]
Yup, done!
