### ISSUE TITLE
GitHub Gist URLs not working

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/graphgist-cms#44]
When I paste an URL like this: `https://gist.github.com/ikwattro/a080ce918a3c87bf3979`
it causes an JS error in the console:

    gist.js:102 Uncaught ReferenceError: useGithubGist is not defined

**Comment by jexp** [comment]
also when you submit graphgist urls like this: http://gist.neo4j.org/?8810771

**Comment by cheerfulstoic** [comment]
Fixed now.  Sorry about that!
