### ISSUE TITLE
Make Render Link for GraphGists more prominent

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/graphgist-cms#50]
People don't see it, perhaps make it a button too and demote the page-source button to something less adamant?

Also make the image clickable to bring up the graphgist page.

**Comment by cheerfulstoic** [comment]
Done and done!  While I was in the neighborhood I added a "Loading" text indicator on the gist page to show that the AJAX is being loaded.  Also, if it fails it will change the text to an error so that the user doesn't need to wait around.
