### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by aileenrose** [neo4j-contrib/graphgist-cms#52]
<script type="text/javascript">

    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    //Allow Linker 
    ga('create', 'UA-1192232-34','auto', {'allowLinker': true});
    ga('send', 'pageview');

    // Load the plugin.
    ga('require', 'linker');
 
    // Define which domains to autoLink.
    ga('linker:autoLink', ['neo4j.org','neo4j.com','neotechnology.com','graphdatabases.com','graphconnect.com']);
  </script>

**Comment by cheerfulstoic** [comment]
Done!

Could I get access to it?  public@brian-underwood.codes
