### ISSUE TITLE
icons for expand, collaps, fullscreen, download not visible

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/graphgist-cms#53]
Perhaps the icon stylesheet/font is not loading?

compare:
http://graphgist.neo4j.com/#!/gists/6932503f597123876c43a778fba85eaa

and
http://gist.neo4j.org/?8635758

**Comment by cheerfulstoic** [comment]
Interesting, I saw at least some of them previously.  I'll look now.

**Comment by cheerfulstoic** [comment]
Looks like I missed these icons.  They're there now.  I changed the plus/minus icons to expand/collapse arrows.  Let me know if you like any other of the glyphicons better:

http://getbootstrap.com/components/

**Comment by jexp** [comment]
Cool, thanks a lot.
