### ISSUE TITLE
Link from manage page to gist

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4j-contrib/graphgist-cms#54]
Maybe privileged link from gist page to manage page somehow?

**Comment by jexp** [comment]
I actually meant the other way round from the manage page to the gist rendering.

**Comment by cheerfulstoic** [comment]
Yeah, for sure.  I made that the title, but was speculating about linking from the rendering page, but of course only if it were possible to do that only for admins.  At the moment we don't have user accounts, so I don't think it's possible

**Comment by jexp** [comment]
I didn't see the change? Is it done or "made" future intent ? :)

**Comment by cheerfulstoic** [comment]
"made" was referring to me making the title of this github issue.
