### ISSUE TITLE
No Title is shown on the graph-gist render page

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/graphgist-cms#62]
* [ ] The HTML <title> is currently a generic "PageSource Neo4j GraphGist"
* [ ] There is no h1 or h2 title above the graphgist
* [ ] the breadcrumbs miss the title too

![skitch-1](https://cloud.githubusercontent.com/assets/67427/6145377/7ce31f66-b1e1-11e4-995e-d463159d5dc8.png)

**Comment by cheerfulstoic** [comment]
Ah, good catch.  Need to parse the asciidoc for the header for this, I guess.  Can check to see how gist.neo4j.org does this.

**Comment by jexp** [comment]
Just with JQuery but I think a Title field should be in the GraphGist node, or?

**Comment by cheerfulstoic** [comment]
When the gist is in the database then it works fine, but that gist isn't in the database

**Comment by jexp** [comment]
then $("h2") or h1 ... from the title of the gist itself.

**Comment by cheerfulstoic** [comment]
Maybe, though in the case of my gist the title is in the frontmatter (or whatever it's called, that's what the data at the top of the file is called in Jekyll).

If you look at the gist on github it has no title:
https://gist.github.com/cheerfulstoic/7e8ec61f9104017430af

But the raw file has a title at the top:
https://gist.githubusercontent.com/cheerfulstoic/7e8ec61f9104017430af/raw/7c92d748fa36d878a39b01ca57479c35d2f282a2/gistfile1.asciidoc

It's followed by the `:Author:`, `:Email:`, etc... so I guess that makes it special.  I was thinking that the asciidoc parser might make it accessible, but it seems like it strips it out.  I think that's how to specify a title for the document and I was following the graphgist instruction gist

**Comment by cheerfulstoic** [comment]
Looks like the ruby library takes a `showtitle` option.  Need to figure out how to use it in node, but stepping away for a bit now

**Comment by cheerfulstoic** [comment]
This is fixed now for graphgists which aren't in the DB

**Comment by cheerfulstoic** [comment]
Oh, right, I forgot about this issue:

http://graphgist.neo4j.com/#!/gists/f38a466e9a518927202fc1dd37858f52

Title is appearing twice.  I think this might have been happening before, but it's worth a look

**Comment by cheerfulstoic** [comment]
The issue with that Gist is that the header is an h2, not an h1...  I don't think that this would be very easy to fix but it's easy to fix the Gists

**Comment by ryguyrg** [comment]
Confused, as the exact same Gist source is displaying a title when
accessing it through the other path (gist.github.com).

Cheers,
-Ryan



On Fri, Jun 5, 2015 at 10:45 AM, Brian Underwood <notifications@github.com>
wrote:

> Closed #62 <https://github.com/neo4j-contrib/graphgist-cms/issues/62>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/neo4j-contrib/graphgist-cms/issues/62#event-323810710>
> .
>



-- 
ryan boyd
twitter: @ryguyrg
<http://t.sidekickopen05.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2BgXCFN5v0L0PdDL-bW3LyyXR56dGlrf5mkGST02?t=http%3A%2F%2Fwww.twitter.com%2Fryguyrg&si=5299090570608640&pi=2fc54d67-dbd7-4e3f-8ce9-a5a597b7954f>
my book: Getting Started with OAuth 2.0
<http://t.sidekickopen05.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2BgXCFN5v0L0PdDL-bW3LyyXR56dGlrf5mkGST02?t=http%3A%2F%2Fgoo.gl%2FO7K3Y&si=5299090570608640&pi=2fc54d67-dbd7-4e3f-8ce9-a5a597b7954f>
my website: http://www.developeradvocate.com/

**Comment by cheerfulstoic** [comment]
The asciidoctor plugin for Node doesn't recognize the header as a title when it's an h2 (in this case it has two equal characters).  Does that make sense?

**Comment by ryguyrg** [comment]
I understand what you're saying about it not recognizing it when it's a h2.

What I don't understand is that, regardless of the URL submitted, I would
expect the gist source to be retrieved and then processed through the same
pipeline.

So, that Gist is hosted at two different places, one on gist.github.com and
one in a normal github repo. After GraphGist retrieves the AsciiDoc source
via (slightly different) API calls to GitHub, I don't understand why it
would go through different rendering pipelines causing the title to be
rendered differently given the exact same adoc content.

Am I explaining my confusion in a non-confusing way? :-)



On Friday, June 5, 2015, Brian Underwood <notifications@github.com> wrote:

> The asciidoctor plugin for Node doesn't recognize the header as a title
> when it's an h2 (in this case it has two equal characters). Does that make
> sense?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/neo4j-contrib/graphgist-cms/issues/62#issuecomment-109514055>
> .
>


-- 
ryan boyd
twitter: @ryguyrg <http://www.twitter.com/ryguyrg>
my book: Getting Started with OAuth 2.0 <http://goo.gl/O7K3Y>
my website: http://www.developeradvocate.com/

**Comment by cheerfulstoic** [comment]
Ah, I don't think we're talking about the same thing ;)  I'm not talking about the gist that we were talking about earlier that was both in a github repo and on gist.github.com.  I'm just talking about the most recent gist that I mentioned in this thread ( http://graphgist.neo4j.com/#!/gists/f38a466e9a518927202fc1dd37858f52 ).  As far as I know the result should be the same coming from either a repo or gist.github.com
