### ISSUE TITLE
GraphGist Page Title is "<title>Page Source"

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/graphgist-cms#65]

**Comment by cheerfulstoic** [comment]
I'm not able to reproduce this... What browser / URL?

**Comment by jexp** [comment]
Not literally `<title>` but "This is a gist titlePage Source"

Chrome, OSX

**Comment by cheerfulstoic** [comment]
Sorry, I'm still not able to reproduce...  I'm seeing the gist's title as the <title> of the page wherever I go wether it's in the DB or not.  What URL are you using?  Or is it happening all over?

**Comment by jexp** [comment]
It's on the browser tab

Von meinem iPhone gesendet

**Comment by cheerfulstoic** [comment]
Ah!  I see it now!  Sorry, I misunderstood what you were saying and the pages that I were checking had titles that were longer than the tab.  I'll fix it now!  Thanks

**Comment by jexp** [comment]
Sorry my bad for being not clearer 

Von meinem iPhone gesendet

**Comment by cheerfulstoic** [comment]
My fault for not reading carefully enough.  Fixed now
