### ISSUE TITLE
GraphGist summary images don't display if wrong link submitted

### ISSUE THREAD

**Issue by DrDavidJ** [neo4j-contrib/graphgist-cms#68]
Images that were submitted with incorrect link fail to display on GraphGist summary page. For example on http://graphgist.neo4j.com/#!/gists/b33f7bea76547f475aa71d7847ce2ddc/summary I submitted the image link https://www.dropbox.com/s/dly6wxgwpf053op/olympics-graphgist.png?dl=0 which doesn't work (should be https://www.dropbox.com/s/dly6wxgwpf053op/olympics-graphgist.png?dl=1 to display). But same case would happen with any other broken link I think. It would be good if there was a method or procedure to report broken image links or to update info after submission.

**Comment by cheerfulstoic** [comment]
Thanks for the report!  I've fixed your gist's image.  I've also put in a bit of javascript that replaces images with a link to this repo's "New Issue" page so that people can report them here.
