### ISSUE TITLE
Page is grey when loading

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4j-contrib/graphgist-cms#75]

**Comment by jexp** [comment]
@cheerfulstoic also the issue you resolved already once with the search-box shows up again, prob. due to some CSS removal?

![fullscreen](https://cloud.githubusercontent.com/assets/67427/7396151/202080c0-ee9f-11e4-87c8-fce5d3b3d922.jpg)

**Comment by cheerfulstoic** [comment]
Looks like that CSS went missing as part of the refactoring.  I've just put it back.  I also just fixed the grey page on load.  I think some sort of loading indicator makes sense on single page apps like this since the browser doesn't tell you that the page is loading, but obviously it's not consistent with the neo4j.com experience
