### ISSUE TITLE
Line-Wrap for tables with row selector/search box

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/graphgist-cms#79]
![beers and breweries - neo4j graphgist-1](https://cloud.githubusercontent.com/assets/67427/7402144/e7cf4cbc-eec9-11e4-8de6-c9b35fdc71a3.jpg)

**Comment by cheerfulstoic** [comment]
Done.  Here's a simple preview gist for this purpose:

http://graphgist.neo4j.com/#!/gists/d8a32994f1869de411f2
