### ISSUE TITLE
Mathjax is broken

### ISSUE THREAD

**Issue by whatSocks** [neo4j-contrib/graphgist-cms#89]
Examples of broken mathjax

http://graphgist.neo4j.com/#!/gists/eab6dca75f701444987d709f4b0217e1
http://graphgist.neo4j.com/#!/gists/c76c5a2d8835fac7d58484fb7c1bc70d
http://graphgist.neo4j.com/#!/gists/6889603496bfde58a2716f7506bb7be1

**Comment by cheerfulstoic** [comment]
Sorry about that!  It's fixed now.  Please re-open if it's still a problem
